[[collection]]
type = "art"
img = "/figs/writeHeightUI.webp"
title = "WriteHeight"
link = "https://edibotopic.github.io/write-height/"
content = "Tool for making 3D models from grayscale images."

[[collection]]
type = "art"
img = "/figs/stokesLawUI.webp"
title = "Stokes’ law visualiser"
link = "https://edibotopic.github.io/stokes-law/"
content = "Interactive particle simulation to teach the principles of Stokes’ law."

[[collection]]
type = "art"
img = "/figs/tierListUI.webp"
title = "TierList"
link = "https://edibotopic.github.io/tier-list/"
content = "Tool that is sufficient to make good tier lists."
